jobs:

  - name: runSh_1
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: nginx-image
      - TASK:
        - script: sleep 10
        
  - name: runSh_2
    type: runSh
    steps:
      - IN: runSh_1
      - TASK:
        - script: sleep 1
    flags:
        - flag_pipe1
  - name: runSh_3
    type: runSh
    steps:
      - IN: runSh_2
      - TASK:
        - script: sleep 1   
