jobs:

  - name: runSh_1
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: nginx-image
      - TASK:
        - script: sleep 10
        
  - name: runSh_2
    type: runSh
    steps:
      - IN: runSh_1
      - TASK:
        - script: sleep 1
    flags:
        - flag1
        - flag2
        - flag3
  - name: runSh_3
    type: runSh
    steps:
      - IN: runSh_2
      - TASK:
        - script: sleep 1   
        
  - name: runSh_4
    type: runSh
    steps:
      - IN: runSh_3
      - IN: time-trigger
      - TASK:
        - script: sleep 1
        
  - name: runSh_5
    type: runSh
    steps:
      - TASK:
        - script: sleep 1           
        
  - name: runSh_6
    type: runSh
    steps:
      - IN: runSh_5
      - TASK:
        - script: sleep 1
